# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ratemonitor', ['core', 'internet', 'point-to-point', 'csma', \
            'applications', 'network', 'traffic-control', 'tap-bridge', 'minibox', 'mbox'])
    module.source = [
        'model/ratemonitor.cc',
        'helper/ratemonitor-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ratemonitor')
    module_test.source = [
        'test/ratemonitor-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ratemonitor'
    headers.source = [
        'model/ratemonitor.h',
        'model/mrun.h',
        'helper/ratemonitor-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

